version: '3.7'

services:
  app:
    image: alexmasyukov/klumba_app:latest
    container_name: app
    networks:
      - proxy.front-network
    expose:
      - 80
    restart: always

  cms:
    image: alexmasyukov/klumba_cms:latest
    container_name: cms
    networks:
      - proxy.front-network
      - db
    restart: always


  viber-bot:
    image: alexmasyukov/klumba_viber_bot:latest
    container_name: viber-bot
    env_file:
      - ./bot-viber/.env
    networks:
      - proxy.front-network
      - db
    environment:
      - NODE_ENV=production
    expose:
      - 9999
    depends_on:
      - postgres
    restart: always


#  tbot:
#    container_name: tbot
#    image: alexmasyukov/klumba_tbot:latest
#    networks:
#      - proxy.front-network
#      - db
#    volumes:
#      - './telegram-bot:/app'
#      - '/app/node_modules'
#    environment:
#      - NODE_ENV=development
#    ports:
#      - 5000:3500
#    restart: always

  api:
    image: alexmasyukov/klumba_api:latest
    container_name: api
#    env_file:
#      - ./server/.env
    networks:
      - proxy.front-network
      - db
    environment:
      - NODE_ENV=production
    expose:
      - 3500
    restart: always

  postgres:
    image: postgres:12.2
    container_name: postgres
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: klumba
    #            PGDATA: OLD /data/postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 7878:5432
    networks:
      - db
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    networks:
      - proxy.front-network
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/log:/var/log/letsencrypt/
    restart: unless-stopped
    entrypoint:  "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # Проверяет каждые 12 часов, нужны ли новые сертификаты

  nginx:
    image: nginx:1.17.9-alpine
    container_name: nginx
    networks:
      #      - front
      #      - db
      - proxy.front-network
    depends_on:
      - postgres
      - api
      - app
      - cms
    volumes:
      - ./settings/nginx:/etc/nginx/conf.d
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
      - 5000:5000
    restart: unless-stopped
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    # Перезапустит nginx контейнер каждые 6 часов и подгрузит новые сертификаты, если есть

networks:
  #  front:
  #    name: front
  db:
    driver: bridge
  proxy.front-network:
    driver: bridge



#  docker-compose -f docker-compose.prod.yml up --build

#  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
#  pgadmin     |     return util.import_app(self.app_uri)