version: '3.7'

services:
#  app:
#    container_name: app
#    build:
#      context: ./client
#      dockerfile: Dockerfile.prod

  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile.prod

  api-test:
    image: klumba_api:latest
    container_name: api
    networks:
      - front
    environment:
      - NODE_ENV=production
    ports:
      - 3500:3500
    restart: always


networks:
  front:
    name: front