version: '3.7'

services:
  app:
    container_name: app
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    image: alexmasyukov/klumba_app:latest
    environment:
      - PUBLIC_URL=/

#  cms:
#    container_name: cms
#    build:
#      context: ./cmslite
#      dockerfile: Dockerfile.prod
##    image: alexmasyukov/klumba_cms:latest
#    volumes:
#      - './cmslite:/app'
#      - '/app/node_modules'
#    ports:
#      - 4000:4000
#    environment:
#      - NODE_ENV=production
#      - PUBLIC_URL=/

#  cms-test:
#    container_name: cms-test
#    image: alexmasyukov/klumba_cms:latest
#    networks:
#      - front
#    environment:
#      - NODE_ENV=production
#      - PUBLIC_URL=/
#    expose:
#      - 4000
#    ports:
#      - 4000:4000
#    restart: always

  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    image: alexmasyukov/klumba_api:latest
    environment:
      - NODE_ENV=production


  tbot:
    container_name: tbot
    image: alexmasyukov/klumba_tbot:latest
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile.dev
    volumes:
      - './telegram-bot:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
    #      - CHOKIDAR_USEPOLLING=true
    restart: always

  api-test:
    image: klumba_api:latest
    container_name: api
    networks:
      - front
    environment:
      - NODE_ENV=production
    ports:
      - 3500:3500
    restart: always


networks:
  front:
    name: front