version: '3.7'

services:

  app-dev:
    container_name: app-dev
    networks:
      - front
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:80
    environment:
      - CHOKIDAR_USEPOLLING=true


networks:
  front:
    name: front

# https://mherman.org/blog/dockerizing-a-react-app/