version: '3.7'

services:
  app-dev:
    container_name: app-dev
    networks:
      - db
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - './client:/app'
      - '/app/node_modules'
    #    ports:
    #      - 3000:3000
    environment:
      - NODE_ENV=development
      - PUBLIC_URL=/
  #      - CHOKIDAR_USEPOLLING=true
  #    env_file:
  #      - ./common.env
  #      - ./apps/web.env
  #      - /opt/runtime_opts.env
  #    logging:
  #      driver: syslog
  #      options:
  #        syslog-address: "tcp://192.168.0.42:123"
  #        max-size: "200k"
  #        max-file: "10"
  #      logging:
  #        driver: "json-file"
  #        options:
  #          max-size: "200k"
  #          max-file: "10"

  cms-dev:
    container_name: cms-dev
    stdin_open: true
#    tty: true
    networks:
      - db
    build:
      context: ./cmslite
      dockerfile: Dockerfile.dev
    volumes:
      - './cmslite:/cms'
      - '/cms/node_modules'
    environment:
      - NODE_ENV=development
      - PORT=5000
      - PUBLIC_URL=/


#  smtp-dev:
#    image: namshi/smtp:latest
#    container_name: smtp-dev
#    environment:
#      PORT: 25
#    expose:
#      - 25
#    networks:
#      - db
#    restart: always


  bot-viber-dev:
    container_name: bot-viber-dev
    networks:
      - db
      - front
    env_file:
      - ./bot-viber/dev.env
    build:
      context: ./bot-viber
      dockerfile: Dockerfile.dev
    volumes:
      - './bot-viber:/app'
      - '/app/node_modules'
    ports:
      - 9999:9999
    depends_on:
      - postgres-dev
    # restart: always


  api-dev:
    container_name: api-dev
    networks:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - './server:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
    #      - CHOKIDAR_USEPOLLING=true
    restart: always


  postgres-dev:
    image: postgres:12.2-alpine
    container_name: postgres-dev
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: klumba
    #            PGDATA: OLD /data/postgres_dev
    volumes:
      - ./data/postgres_dev:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 7878:5432
    networks:
      - db
    restart: always


  nginx-dev:
    image: nginx:1.17.9-alpine
    container_name: nginx-dev
    networks:
      - db
    depends_on:
      - postgres-dev
#      - bot-viber-dev
      - api-dev
      - app-dev
      - cms-dev
    volumes:
      - ./settings/nginx_dev:/etc/nginx/conf.d
    ports:
      - 80:80
      - 5000:5000
    restart: always


networks:
  front:
    name: front
  db:
    name: db
    driver: bridge

# https://mherman.org/blog/dockerizing-a-react-app/