FROM node:12-alpine
WORKDIR /app
COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock
ENV PATH /app/node_modules/.bin:$PATH
RUN yarn
EXPOSE 9999
CMD [ "nodemon", "--unhandled-rejections=none", "index.js"]