version: '3.7'

services:

  app-prod:
    image: app-image
    container_name: app-prod
    networks:
      - front
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - 5000:80
    restart: unless-stopped


networks:
  front:
    name: front


#  docker-compose -f docker-compose.prod.yml up --build