# build environment
FROM node:12-alpine as build
WORKDIR /app
COPY .env /app/.env
COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock
ENV PATH /app/node_modules/.bin:$PATH
RUN yarn
EXPOSE 3500
CMD [ "nodemon", "index.js" ]