# build environment
FROM node:12-alpine as build
WORKDIR /app
COPY package.json yarn.lock ./
ENV PATH /app/node_modules/.bin:$PATH
RUN yarn
COPY . /app
RUN yarn build

# production environment
FROM nginx:1.17.9-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 5000
CMD ["nginx", "-g", "daemon off;"]